version: "3"

services:
  web:
    build:
      context: ./web
      dockerfile: docker/Dockerfile
    container_name: 'challenge-web'
    ports:
      - '80:80'
    volumes:
      - ./web/:/var/www/
      - ./web/log/web/:/var/log/web/
      - ./web/log/apache2/:/var/log/apache2/
      - /etc/hosts:/etc/hosts
    depends_on:
      - database
    networks:
      - backend
  database:
    image: 'mongo'
    container_name: 'mongo-db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=challengedb
      - MONGODB_DATA_DIR=/data/db
    volumes:
      - ./web/docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - '27017:27017'
    networks:
      - backend
#TODO: check if network is needed
networks:
    backend:
        driver: bridge
